// Types
export type BookInfo = {
  name: string;
  chapters: number;
};

export type LanguageBooks = {
  [index: number]: BookInfo;
};

export type BibleBooksDictType = {
  en: LanguageBooks;
  fr: LanguageBooks;
  es: LanguageBooks;
  ht: LanguageBooks;
};

export const BibleBooksDict: BibleBooksDictType = {
  en: {
    1: { name: 'Genesis', chapters: 50 },
    2: { name: 'Exodus', chapters: 40 },
    3: { name: 'Leviticus', chapters: 27 },
    4: { name: 'Numbers', chapters: 36 },
    5: { name: 'Deuteronomy', chapters: 34 },
    6: { name: 'Joshua', chapters: 24 },
    7: { name: 'Judges', chapters: 21 },
    8: { name: 'Ruth', chapters: 4 },
    9: { name: '1 Samuel', chapters: 31 },
    10: { name: '2 Samuel', chapters: 24 },
    11: { name: '1 Kings', chapters: 22 },
    12: { name: '2 Kings', chapters: 25 },
    13: { name: '1 Chronicles', chapters: 29 },
    14: { name: '2 Chronicles', chapters: 36 },
    15: { name: 'Ezra', chapters: 10 },
    16: { name: 'Nehemiah', chapters: 13 },
    17: { name: 'Esther', chapters: 10 },
    18: { name: 'Job', chapters: 42 },
    19: { name: 'Psalms', chapters: 150 },
    20: { name: 'Proverbs', chapters: 31 },
    21: { name: 'Ecclesiastes', chapters: 12 },
    22: { name: 'Song of Solomon', chapters: 8 },
    23: { name: 'Isaiah', chapters: 66 },
    24: { name: 'Jeremiah', chapters: 52 },
    25: { name: 'Lamentations', chapters: 5 },
    26: { name: 'Ezekiel', chapters: 48 },
    27: { name: 'Daniel', chapters: 12 },
    28: { name: 'Hosea', chapters: 14 },
    29: { name: 'Joel', chapters: 3 },
    30: { name: 'Amos', chapters: 9 },
    31: { name: 'Obadiah', chapters: 1 },
    32: { name: 'Jonah', chapters: 4 },
    33: { name: 'Micah', chapters: 7 },
    34: { name: 'Nahum', chapters: 3 },
    35: { name: 'Habakkuk', chapters: 3 },
    36: { name: 'Zephaniah', chapters: 3 },
    37: { name: 'Haggai', chapters: 2 },
    38: { name: 'Zechariah', chapters: 14 },
    39: { name: 'Malachi', chapters: 4 },
    40: { name: 'Matthew', chapters: 28 },
    41: { name: 'Mark', chapters: 16 },
    42: { name: 'Luke', chapters: 24 },
    43: { name: 'John', chapters: 21 },
    44: { name: 'Acts', chapters: 28 },
    45: { name: 'Romans', chapters: 16 },
    46: { name: '1 Corinthians', chapters: 16 },
    47: { name: '2 Corinthians', chapters: 13 },
    48: { name: 'Galatians', chapters: 6 },
    49: { name: 'Ephesians', chapters: 6 },
    50: { name: 'Philippians', chapters: 4 },
    51: { name: 'Colossians', chapters: 4 },
    52: { name: '1 Thessalonians', chapters: 5 },
    53: { name: '2 Thessalonians', chapters: 3 },
    54: { name: '1 Timothy', chapters: 6 },
    55: { name: '2 Timothy', chapters: 4 },
    56: { name: 'Titus', chapters: 3 },
    57: { name: 'Philemon', chapters: 1 },
    58: { name: 'Hebrews', chapters: 13 },
    59: { name: 'James', chapters: 5 },
    60: { name: '1 Peter', chapters: 5 },
    61: { name: '2 Peter', chapters: 3 },
    62: { name: '1 John', chapters: 5 },
    63: { name: '2 John', chapters: 1 },
    64: { name: '3 John', chapters: 1 },
    65: { name: 'Jude', chapters: 1 },
    66: { name: 'Revelation', chapters: 22 },
  },
  fr: {
    1: { name: 'Genèse', chapters: 50 },
    2: { name: 'Exode', chapters: 40 },
    3: { name: 'Lévitique', chapters: 27 },
    4: { name: 'Nombres', chapters: 36 },
    5: { name: 'Deutéronome', chapters: 34 },
    6: { name: 'Josué', chapters: 24 },
    7: { name: 'Juges', chapters: 21 },
    8: { name: 'Ruth', chapters: 4 },
    9: { name: '1 Samuel', chapters: 31 },
    10: { name: '2 Samuel', chapters: 24 },
    11: { name: '1 Rois', chapters: 22 },
    12: { name: '2 Rois', chapters: 25 },
    13: { name: '1 Chroniques', chapters: 29 },
    14: { name: '2 Chroniques', chapters: 36 },
    15: { name: 'Esdras', chapters: 10 },
    16: { name: 'Néhémie', chapters: 13 },
    17: { name: 'Esther', chapters: 10 },
    18: { name: 'Job', chapters: 42 },
    19: { name: 'Psaumes', chapters: 150 },
    20: { name: 'Proverbes', chapters: 31 },
    21: { name: 'Ecclésiaste', chapters: 12 },
    22: { name: 'Cantique des Cantiques', chapters: 8 },
    23: { name: 'Ésaïe', chapters: 66 },
    24: { name: 'Jérémie', chapters: 52 },
    25: { name: 'Lamentations', chapters: 5 },
    26: { name: 'Ézéchiel', chapters: 48 },
    27: { name: 'Daniel', chapters: 12 },
    28: { name: 'Osée', chapters: 14 },
    29: { name: 'Joël', chapters: 3 },
    30: { name: 'Amos', chapters: 9 },
    31: { name: 'Abdias', chapters: 1 },
    32: { name: 'Jonas', chapters: 4 },
    33: { name: 'Michée', chapters: 7 },
    34: { name: 'Nahum', chapters: 3 },
    35: { name: 'Habacuc', chapters: 3 },
    36: { name: 'Sophonie', chapters: 3 },
    37: { name: 'Aggée', chapters: 2 },
    38: { name: 'Zacharie', chapters: 14 },
    39: { name: 'Malachie', chapters: 4 },
    40: { name: 'Matthieu', chapters: 28 },
    41: { name: 'Marc', chapters: 16 },
    42: { name: 'Luc', chapters: 24 },
    43: { name: 'Jean', chapters: 21 },
    44: { name: 'Actes', chapters: 28 },
    45: { name: 'Romains', chapters: 16 },
    46: { name: '1 Corinthiens', chapters: 16 },
    47: { name: '2 Corinthiens', chapters: 13 },
    48: { name: 'Galates', chapters: 6 },
    49: { name: 'Éphésiens', chapters: 6 },
    50: { name: 'Philippiens', chapters: 4 },
    51: { name: 'Colossiens', chapters: 4 },
    52: { name: '1 Thessaloniciens', chapters: 5 },
    53: { name: '2 Thessaloniciens', chapters: 3 },
    54: { name: '1 Timothée', chapters: 6 },
    55: { name: '2 Timothée', chapters: 4 },
    56: { name: 'Tite', chapters: 3 },
    57: { name: 'Philémon', chapters: 1 },
    58: { name: 'Hébreux', chapters: 13 },
    59: { name: 'Jacques', chapters: 5 },
    60: { name: '1 Pierre', chapters: 5 },
    61: { name: '2 Pierre', chapters: 3 },
    62: { name: '1 Jean', chapters: 5 },
    63: { name: '2 Jean', chapters: 1 },
    64: { name: '3 Jean', chapters: 1 },
    65: { name: 'Jude', chapters: 1 },
    66: { name: 'Apocalypse', chapters: 22 },
  },
  es: {
    1: { name: 'Génesis', chapters: 50 },
    2: { name: 'Éxodo', chapters: 40 },
    3: { name: 'Levítico', chapters: 27 },
    4: { name: 'Números', chapters: 36 },
    5: { name: 'Deuteronomio', chapters: 34 },
    6: { name: 'Josué', chapters: 24 },
    7: { name: 'Jueces', chapters: 21 },
    8: { name: 'Rut', chapters: 4 },
    9: { name: '1 Samuel', chapters: 31 },
    10: { name: '2 Samuel', chapters: 24 },
    11: { name: '1 Reyes', chapters: 22 },
    12: { name: '2 Reyes', chapters: 25 },
    13: { name: '1 Crónicas', chapters: 29 },
    14: { name: '2 Crónicas', chapters: 36 },
    15: { name: 'Esdras', chapters: 10 },
    16: { name: 'Nehemías', chapters: 13 },
    17: { name: 'Ester', chapters: 10 },
    18: { name: 'Job', chapters: 42 },
    19: { name: 'Salmos', chapters: 150 },
    20: { name: 'Proverbios', chapters: 31 },
    21: { name: 'Eclesiastés', chapters: 12 },
    22: { name: 'Cantar de los Cantares', chapters: 8 },
    23: { name: 'Isaías', chapters: 66 },
    24: { name: 'Jeremías', chapters: 52 },
    25: { name: 'Lamentaciones', chapters: 5 },
    26: { name: 'Ezequiel', chapters: 48 },
    27: { name: 'Daniel', chapters: 12 },
    28: { name: 'Oseas', chapters: 14 },
    29: { name: 'Joel', chapters: 3 },
    30: { name: 'Amós', chapters: 9 },
    31: { name: 'Abdías', chapters: 1 },
    32: { name: 'Jonás', chapters: 4 },
    33: { name: 'Miqueas', chapters: 7 },
    34: { name: 'Nahúm', chapters: 3 },
    35: { name: 'Habacuc', chapters: 3 },
    36: { name: 'Sofonías', chapters: 3 },
    37: { name: 'Hageo', chapters: 2 },
    38: { name: 'Zacarías', chapters: 14 },
    39: { name: 'Malaquías', chapters: 4 },
    40: { name: 'Mateo', chapters: 28 },
    41: { name: 'Marcos', chapters: 16 },
    42: { name: 'Lucas', chapters: 24 },
    43: { name: 'Juan', chapters: 21 },
    44: { name: 'Hechos', chapters: 28 },
    45: { name: 'Romanos', chapters: 16 },
    46: { name: '1 Corintios', chapters: 16 },
    47: { name: '2 Corintios', chapters: 13 },
    48: { name: 'Gálatas', chapters: 6 },
    49: { name: 'Efesios', chapters: 6 },
    50: { name: 'Filipenses', chapters: 4 },
    51: { name: 'Colosenses', chapters: 4 },
    52: { name: '1 Tesalonicenses', chapters: 5 },
    53: { name: '2 Tesalonicenses', chapters: 3 },
    54: { name: '1 Timoteo', chapters: 6 },
    55: { name: '2 Timoteo', chapters: 4 },
    56: { name: 'Tito', chapters: 3 },
    57: { name: 'Filemón', chapters: 1 },
    58: { name: 'Hebreos', chapters: 13 },
    59: { name: 'Santiago', chapters: 5 },
    60: { name: '1 Pedro', chapters: 5 },
    61: { name: '2 Pedro', chapters: 3 },
    62: { name: '1 Juan', chapters: 5 },
    63: { name: '2 Juan', chapters: 1 },
    64: { name: '3 Juan', chapters: 1 },
    65: { name: 'Judas', chapters: 1 },
    66: { name: 'Apocalipsis', chapters: 22 },
  },
  ht: {
    1: { name: 'Jenèz', chapters: 50 },
    2: { name: 'Egzòd', chapters: 40 },
    3: { name: 'Levitik', chapters: 27 },
    4: { name: 'Nimewo', chapters: 36 },
    5: { name: 'Detewonòm', chapters: 34 },
    6: { name: 'Jozye', chapters: 24 },
    7: { name: 'Jij', chapters: 21 },
    8: { name: 'Rout', chapters: 4 },
    9: { name: '1 Samyèl', chapters: 31 },
    10: { name: '2 Samyèl', chapters: 24 },
    11: { name: '1 Wa', chapters: 22 },
    12: { name: '2 Wa', chapters: 25 },
    13: { name: '1 Kwonik', chapters: 29 },
    14: { name: '2 Kwonik', chapters: 36 },
    15: { name: 'Ezra', chapters: 10 },
    16: { name: 'Neemi', chapters: 13 },
    17: { name: 'Estè', chapters: 10 },
    18: { name: 'Job', chapters: 42 },
    19: { name: 'Sòm', chapters: 150 },
    20: { name: 'Pwovèb', chapters: 31 },
    21: { name: 'Eklezyas', chapters: 12 },
    22: { name: 'Chante Chante', chapters: 8 },
    23: { name: 'Esaïe', chapters: 66 },
    24: { name: 'Jeremi', chapters: 52 },
    25: { name: 'Chagren', chapters: 5 },
    26: { name: 'Ezèkiel', chapters: 48 },
    27: { name: 'Daniel', chapters: 12 },
    28: { name: 'Oze', chapters: 14 },
    29: { name: 'Joel', chapters: 3 },
    30: { name: 'Amòs', chapters: 9 },
    31: { name: 'Abdi', chapters: 1 },
    32: { name: 'Jonas', chapters: 4 },
    33: { name: 'Mika', chapters: 7 },
    34: { name: 'Nahòm', chapters: 3 },
    35: { name: 'Abakouk', chapters: 3 },
    36: { name: 'Sofoni', chapters: 3 },
    37: { name: 'Agaw', chapters: 2 },
    38: { name: 'Zakari', chapters: 14 },
    39: { name: 'Malachi', chapters: 4 },
    40: { name: 'Matye', chapters: 28 },
    41: { name: 'Mak', chapters: 16 },
    42: { name: 'Lik', chapters: 24 },
    43: { name: 'Jan', chapters: 21 },
    44: { name: 'Travay Apot yo', chapters: 28 },
    45: { name: 'Women', chapters: 16 }, // Romans → Women? Should be "Women"? We'll fix below
    46: { name: '1 Korentyen', chapters: 16 },
    47: { name: '2 Korentyen', chapters: 13 },
    48: { name: 'Galat', chapters: 6 },
    49: { name: 'Efez', chapters: 6 },
    50: { name: 'Filipyen', chapters: 4 },
    51: { name: 'Kolosen', chapters: 4 },
    52: { name: '1 Tesalonisyen', chapters: 5 },
    53: { name: '2 Tesalonisyen', chapters: 3 },
    54: { name: '1 Timote', chapters: 6 },
    55: { name: '2 Timote', chapters: 4 },
    56: { name: 'Tit', chapters: 3 },
    57: { name: 'Filemon', chapters: 1 },
    58: { name: 'Ebre', chapters: 13 },
    59: { name: 'Jak', chapters: 5 },
    60: { name: '1 Pyè', chapters: 5 },
    61: { name: '2 Pyè', chapters: 3 },
    62: { name: '1 Jan', chapters: 5 },
    63: { name: '2 Jan', chapters: 1 },
    64: { name: '3 Jan', chapters: 1 },
    65: { name: 'Jid', chapters: 1 },
    66: { name: 'Revelasyon', chapters: 22 },
  },
};

export function listAllBooks(language: string = 'en') {
  const books = BibleBooksDict[language as keyof BibleBooksDictType];
  const result = [];

  for (let index = 1; index <= 66; index++) {
    if (books[index]) {
      result.push({ index, name: books[index].name, chapters: books[index].chapters });
    }
  }

  return result;
}

// Returns an array of chapter numbers for a given book index and language
export function getChaptersByBook(
  language: keyof BibleBooksDictType,
  bookIndex: number,
): { bookName: string; bookIndex: number; chapters: number[] } {
  const book = BibleBooksDict[language][bookIndex];

  if (!book) {
    throw new Error(`Book index ${bookIndex} not found for language ${language}`);
  }

  // Create an array from 1 to book.chapters
  return {
    bookName: book.name,
    bookIndex: bookIndex,
    chapters: Array.from({ length: book.chapters }, (_, i) => i + 1),
  };
}
